//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyFactura
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Ventas")]
    public partial class FacturaDC : object
    {
        
        private string ApellNom_venField;
        
        private string Cod_cliField;
        
        private string Cod_venField;
        
        private short Est_facField;
        
        private string EstadoField;
        
        private System.DateTime Fec_canField;
        
        private System.DateTime Fec_facField;
        
        private string Num_facField;
        
        private string Raz_soc_cliField;
        
        private float TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_ven
        {
            get
            {
                return this.ApellNom_venField;
            }
            set
            {
                this.ApellNom_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_cli
        {
            get
            {
                return this.Cod_cliField;
            }
            set
            {
                this.Cod_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_ven
        {
            get
            {
                return this.Cod_venField;
            }
            set
            {
                this.Cod_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_fac
        {
            get
            {
                return this.Est_facField;
            }
            set
            {
                this.Est_facField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_can
        {
            get
            {
                return this.Fec_canField;
            }
            set
            {
                this.Fec_canField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_fac
        {
            get
            {
                return this.Fec_facField;
            }
            set
            {
                this.Fec_facField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_fac
        {
            get
            {
                return this.Num_facField;
            }
            set
            {
                this.Num_facField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli
        {
            get
            {
                return this.Raz_soc_cliField;
            }
            set
            {
                this.Raz_soc_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyFactura.IServicioFactura")]
    public interface IServicioFactura
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechas", ReplyAction="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechasResponse")]
        System.Collections.Generic.List<ProxyFactura.FacturaDC> ListarFacturasClienteFechas(string strCodigo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechas", ReplyAction="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFactura.FacturaDC>> ListarFacturasClienteFechasAsync(string strCodigo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/ListarFacturasVendedorFechas", ReplyAction="http://tempuri.org/IServicioFactura/ListarFacturasVendedorFechasResponse")]
        System.Collections.Generic.List<ProxyFactura.FacturaDC> ListarFacturasVendedorFechas(string strCodigo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/ListarFacturasVendedorFechas", ReplyAction="http://tempuri.org/IServicioFactura/ListarFacturasVendedorFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFactura.FacturaDC>> ListarFacturasVendedorFechasAsync(string strCodigo, System.DateTime fecini, System.DateTime fecfin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioFacturaChannel : ProxyFactura.IServicioFactura, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioFacturaClient : System.ServiceModel.ClientBase<ProxyFactura.IServicioFactura>, ProxyFactura.IServicioFactura
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturaClient() : 
                base(ServicioFacturaClient.GetDefaultBinding(), ServicioFacturaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioFactura.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturaClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyFactura.FacturaDC> ListarFacturasClienteFechas(string strCodigo, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarFacturasClienteFechas(strCodigo, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFactura.FacturaDC>> ListarFacturasClienteFechasAsync(string strCodigo, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarFacturasClienteFechasAsync(strCodigo, fecini, fecfin);
        }
        
        public System.Collections.Generic.List<ProxyFactura.FacturaDC> ListarFacturasVendedorFechas(string strCodigo, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarFacturasVendedorFechas(strCodigo, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFactura.FacturaDC>> ListarFacturasVendedorFechasAsync(string strCodigo, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarFacturasVendedorFechasAsync(strCodigo, fecini, fecfin);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioFactura))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioFactura))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Ventas/ServicioFactura/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioFactura);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioFactura);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioFactura,
        }
    }
}
